### ISSUE TITLE
Create assessment tool for training sessions

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#12]

**Comment by lovinscari** [comment]
I emailed Instruction Steering Committee to see if they have an assessment tool.

**Comment by eporter23** [comment]
@lovinscari in case this is useful, here is the form we used for Curate training sessions: https://docs.google.com/forms/d/1BvuifgweTPcyjOB6xKZQoqTTagLhPoO_-ue65SncJtA/edit
