### ISSUE TITLE
Develop Blacklight tutorial

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#14]

**Comment by lovinscari** [comment]
From the training sessions with members of the instruction committee, I will provide recordings and slides as a tutorial to deliver to end-users.

**Comment by tmiles2** [comment]
@lovinscari can you place the recordings and slide decks in this folder or at least a copy. Any final artifacts for training should go in this folder. [Training Plans and Artifacts](https://emory-my.sharepoint.com/:f:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Project%20Management/Closing/Deliverables%20-%20Implementation/Organizational%20Change%20Management/Training%20Plan?csf=1&web=1&e=HLA0kg)
