### ISSUE TITLE
Create training plan for pilot users

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#15]

**Comment by lovinscari** [comment]
A training prototype was created and delivered to members of the Instruction Steering Committee. I will be updating information before training on 12/3/21.

**Comment by lovinscari** [comment]
I have worked with members on the Instruction Steering Committee to develop a plan to train members of the Instruction Committee. A session is scheduled for 12/3/21, which will be recorded and also shared with members of the SEND Team. Depending on feedback, another session could be needed if there are too many questions that could not be answered within the 1 hour scheduled.
