### ISSUE TITLE
CPA Accessibility Check

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#22]
I would like to go ahead and run an accessibility test and review the report to see if there are any urgent fixes needed. The majority of the fixes will be planned for Phase 2. As part of Phase 1, I would like for the following tasks to be completed

- [x]  Run Lighthouse on Home Page
- [x]  Run Lighthouse on Advanced Search Page
- [x]  Run Lighthouse on one static page (e.g., About)
- [x]  Run Lighthouse on search results page
- [x]  Run Lighthouse on Single Item View page
- [ ]  Determine next steps for accessibility remediation

**Comment by tmiles2** [comment]
I think this work is postponed until phase 2, can we close this out?

**Comment by lovinscari** [comment]
@tmiles2 - we were going to run the report to see if there are any glaring issues but the overall fixes are planned for Phase 2. I will move this back to backlog.

**Comment by bwatson78** [comment]
@lovinscari For each page, do you want a Mobile and a Desktop based test, or just a Desktop? Lighthouse has different standards for both.

**Comment by bwatson78** [comment]
Desktop Homepage:
![Screen Shot 2021-11-19 at 10.13.55 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a3e3fe4c-54e3-4abb-903d-485b9dc56186)
![Screen Shot 2021-11-19 at 10.14.28 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/81ab7c5d-3b70-43d2-90a2-9f376634618e)
![Screen Shot 2021-11-19 at 10.14.46 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/60f6f297-f2f9-4f10-9a1e-cf1b1a76482a)
![Screen Shot 2021-11-19 at 10.15.18 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/17934b1c-795c-42ca-bbc5-405310103070)
![Screen Shot 2021-11-19 at 10.16.11 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1e9f6b75-2ad2-4b23-88f9-51b47a3a6341)

**Comment by bwatson78** [comment]
Desktop Advanced Search:
![Screen Shot 2021-11-19 at 10.21.09 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8dbfa864-6d30-42c7-ba73-019bfedc58cf)
![Screen Shot 2021-11-19 at 10.21.33 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2b3b8074-767c-4dbe-a1ab-91359b60396d)
![Screen Shot 2021-11-19 at 10.21.53 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/413f82cf-81de-4265-b6e8-3fb2c2a7ae4a)
![Screen Shot 2021-11-19 at 10.22.17 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/231df19d-6af3-45b6-81d5-8d2a81010f6f)
![Screen Shot 2021-11-19 at 10.22.38 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/4801f8dc-6e41-405e-9c3d-c333334ca2b7)

**Comment by bwatson78** [comment]
Desktop About:
![Screen Shot 2021-11-19 at 10.26.52 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2ce970b6-8eb5-4654-96b4-96e3d0f40ba1)
![Screen Shot 2021-11-19 at 10.27.13 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/817d48c5-1577-4747-9db3-3536cfab1fa0)
![Screen Shot 2021-11-19 at 10.27.32 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/42f06f16-c630-432a-aff2-db70304ee93e)
![Screen Shot 2021-11-19 at 10.28.01 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2cbac23e-e6e0-4bac-bc49-9bcd19f99df0)
![Screen Shot 2021-11-19 at 10.28.16 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/acf57ef8-97f7-402f-b9e5-ca416f2b9dbe)

**Comment by bwatson78** [comment]
Desktop Search Results: 
![Screen Shot 2021-11-19 at 10.33.29 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/dcef86fe-fbad-44ed-a1b0-ab37d499efaa)
![Screen Shot 2021-11-19 at 10.34.05 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a5d078e5-f8f8-4294-a27e-d2ca529be4ad)
![Screen Shot 2021-11-19 at 10.34.23 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e406223d-cde3-4a8d-be7c-c6c3245e9ec8)
![Screen Shot 2021-11-19 at 10.35.00 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6e7a4bb1-0997-4e5d-8daf-535e19ba7d29)
![Screen Shot 2021-11-19 at 10.35.34 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/550d4985-6f2d-4e22-b924-2b65047668a8)

**Comment by bwatson78** [comment]
Desktop Single Item View:
![Screen Shot 2021-11-19 at 10.40.59 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b316d989-c478-4192-9e00-ac565c39022a)
![Screen Shot 2021-11-19 at 10.41.21 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/58e7c6b2-d48f-4f10-ab21-970360c8c383)
![Screen Shot 2021-11-19 at 10.41.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a5d5e940-052e-458a-afcc-2130396a4dc1)
![Screen Shot 2021-11-19 at 10.42.01 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f5399664-08cd-4ef2-8b38-9e7e98686357)
![Screen Shot 2021-11-19 at 10.42.17 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0b6013c7-e624-479e-b665-b3b57d493268)

**Comment by bwatson78** [comment]
For Lighthouse reports you can interact with, use this link: https://googlechrome.github.io/lighthouse/viewer/

I will be posting JSON versions of the above reports below.

[Desktop](https://emory-my.sharepoint.com/:f:/g/personal/bwatso9_emory_edu/EgGRt9UdTrJFnEPNruYhfksB4D6qFfnm2fjbGeLi6nlOvA?e=Al9WSc)

[Mobile](https://emory-my.sharepoint.com/:f:/g/personal/bwatso9_emory_edu/Ej_GQKT_OCBOp2Tohs5UgcQBK8-4pbHv-gYyG-2roY9iag?e=KFtaEW)

**Comment by lovinscari** [comment]
This great @bwatson!
