### ISSUE TITLE
ServiceNow CI Setup

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#23]
Add a CI to ServiceNow for Blacklight. This will be needed for operational support.

Use this form to request the CI

https://emory.service-now.com/sp?id=sc_cat_item&sys_id=bc1433751333b6000ec059722244b0ef&sysparm_category=4e6cf5f8414eb00079479fbad28ca8df

**Comment by libdgg** [comment]
@AGCooper @rotated8 The CI will be named BLACKCAT but please add or send alternate names for Blacklight. Here is what I heard in our meeting but want to make sure I get everything.
- Blackcat
- Library Search
- Library Catalog

**Comment by libdgg** [comment]
KB article for the Blacklight Risk Matrix - KB06868
https://emory.service-now.com/nav_to.do?uri=%2Fkb_knowledge.do%3Fsys_id%3Dcf090e2b97fbfc94f5749934a253af06%26sysparm_stack%3Dkb_knowledge_list.do%3Fsysparm_query%3Dactive%3Dtrue

**Comment by lisahamlett** [comment]
KB Submission [SUB12306](https://emory.service-now.com/nav_to.do?uri=%2Fkb_submission.do%3Fsys_id%3D5cab0eef97fbfc94f5749934a253afc8%26sysparm_record_target%3Dtask%26sysparm_record_row%3D2%26sysparm_record_rows%3D2%26sysparm_record_list%3Dactive%253Dtrue%255Eassigned_toISEMPTY%255Eassignment_group%253Djavascript%253AgetMyGroups%2528%2529%255Esys_class_name%2521%253Dsysapproval_group%255Enumber%2521%253DSUB11074%255EORnumber%253DNULL%255EORDERBYDESCsys_created_on) is awaiting for review/revision by Doug.

**Comment by lisahamlett** [comment]
Rose is working on the CI

**Comment by lisahamlett** [comment]
Once I have the CI, I can work with Tony on paging

**Comment by libdgg** [comment]
@lisahamlett submitted the CI request form. Once that is fulfilled the CI will be in place and the ServiceNow KB articles can link to the CI.

**Comment by libdgg** [comment]
I am meeting with Rose Harris this morning and hope to be able to update this ticket after that.

**Comment by libdgg** [comment]
@lisahamlett @lovinscari @tmiles2 @AGCooper 
The CI is setup in ServiceNow with the assignment group of LIB: Core Systems and dependencies on Shibboleth, Alma and Primo so I'm closing this ticket.

CI is here:
https://emory.service-now.com/nav_to.do?uri=%2Fcmdb_ci_appl.do%3Fsys_id%3Dcc1c6e3897cc0910f5749934a253afa8%26sysparm_record_target%3Dcmdb_ci_appl%26sysparm_record_row%3D25%26sysparm_record_rows%3D37%26sysparm_record_list%3Dsys_class_name%253Dcmdb_ci_appl%255Eoperational_status%253D5%255Esupport_group.nameCONTAINSLIB%253A%255EORDERBYname
