### ISSUE TITLE
Create analytics reports and determine how to convey information - Primo VE

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#25]
We have addressed needs around Google Analytics but I would also like to explore what analytics and reports are available through Primo VE. Please reference any information specific to Primo VE analytics  and estimate the amount of effort needed to implement these tools.

**Comment by tmiles2** [comment]
We have google analytic investigation based on what was done with DLP in the current sprint. But this also depends on if we still have Primo, the requirements could change if we remove Primo.

**Comment by tmiles2** [comment]
Cari will rewrite this ticket looking at Primo VE reporting needs.

**Comment by tclayton33** [comment]
related to spike ticket [#1090](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/blacklight-catalog/1090)

**Comment by lovinscari** [comment]
Closing this ticket and will look at adding this to the overall plan for Library Search Reports.
