### ISSUE TITLE
Present information about OLA's to functional working areas 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#28]
- [ ] Once OLA's have been drafted, the information should be shared with the functional working areas including certain members of the SEND Team who are directly involved with operations affecting Library Search such as cataloging, special collections, course reserves, doc delivery, fulfillment, and ILL. 
- [ ] The idea is to have either the feedback form updated to route to these functional areas in the event an issue needs to be reported or have ServiceNow tickets routed to these groups. 
- [ ] Expectations of referred reports should be included in the OLA.

**Comment by tmiles2** [comment]
We will need to meet with Sofia to discuss the cataloging process for content updates. Doug and Cari will start an initial discussion to outline those talking points for an upcoming conversation. We have an existing process for discoverE. 

- We need to include the process in the SLA
- We need to share the information with Sofia (and team), OMT

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
