### ISSUE TITLE
Develop SLA, OLA for Blacklight product

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#29]
Draft OLA 

Setup CI in ServiceNow 

TICKET 262: Confirm Thousandeyes is implemented for paging 

Review OLA with Scrum Team and Product Owner 

LTDS-L Approval of OLA for Beta period 

Schedule 30-day review to review OLA for any adjustments prior to production launch

**Comment by libdgg** [comment]
Duplicate. Closing this one.
