### ISSUE TITLE
Documentation - System Alerts 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#34]
Document why the alerts are in place and what is supposed to happen when an alert is sent/received. (e.g. restart Solr) 

Information reviewers:
- [ ] Alex
- [ ] Collin
- [ ] Ann

**Comment by libdgg** [comment]
Documentation for Blacklight lives in the wiki.

Parent: https://wiki.emory.edu/display/BDL/Technical+Documentation

Alerting: https://wiki.emory.edu/display/BDL/Monitoring+and+Alerts

The documentation for this ticket will be managed via Tickets #39 and #41

**Comment by libdgg** [comment]
The team met today (8/3/21) and built out the wiki space for Operations, Monitor and Alert Definitions and AWS Alerts. We revisited the previous discussions and drafts we had for operations planning and completed a first draft of identifying system monitoring and alerting resources and making the wiki pages for that content. Today's work supports subsequent tickets where we will continue to refine our support workflows and alert work and build on our first drafts in the wiki. The team feels this ticket can close as it served the purpose to get the documentation for support in flight and ready for other tickets to follow. 

https://wiki.emory.edu/display/BDL/Operations
