### ISSUE TITLE
Support: Identify system monitoring and alert resources  

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#35]
- [x] Need to identify people who have knowledge, skills, and abilities for completing certain tasks in AWX when alerts are received.
- [x] Who is on point when an alert comes in (primary, secondary, informational)

**Comment by libdgg** [comment]
This information will be refined in other tickets in the associated epic and [documented in the wiki](https://wiki.emory.edu/display/BDL/Operations). As of June 2021 the model looks like this.

People who have knowledge, skills, and abilities for completing certain tasks in AWX when alerts are received.

First responders
- Ticket reception and triage: Clare Barton, Ann Hulton, Lisa Hamlett, Alex Cooper (Core Systems and on-call schedule)

Ticket/issue escalation
- Infrastructure (AWX, AWS, ExL) will be Systems Admins (2 VACANT)
- Application will be Devanshu Matlawala, Brad Watson, Alexandr Zotov, Collin Brittle
- Escalation in general will be LTDS Directors: Cari Lovins, Doug Goans

Who is on point when an alert comes in (primary, secondary, informational)
- Primary: Core Systems has paging and on call and will do an initial review/assessment. They will use work instructions documented in the wiki for Tier 1-2 troubleshooting to resolve. 
- Secondary: If unable to resolve will triage for resolution to LTDS Middleware and/or Software Development.
- Informational: LTDS TDO teams will utilize ServiceNow comments as the primary communication channel for issues. The team will utilize slack ass a secondary communication channel for any informational or updates on issues.

**Comment by libdgg** [comment]
The team met today (8/3/21) and built out the wiki space for Operations, Monitor and Alert Definitions and AWS Alerts. We revisited the previous discussions and drafts we had for operations planning and completed a first draft of identifying system monitoring and alerting resources and making the wiki pages for that content. Today's work supports subsequent tickets where we will continue to refine our support workflows and alert work and build on our first drafts in the wiki. The team feels this ticket can close as it served the purpose to get the documentation for support in flight and ready for other tickets to follow. 

https://wiki.emory.edu/display/BDL/Operations
