### ISSUE TITLE
Support: Knowledge for Monitoring Matrix

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-launch#41]
Documentation for Blacklight Support lives in the wiki.
https://wiki.emory.edu/display/BDL/Operations
This ticket is to document the current state of the following monitoring tools, what they are, who has access, and what actions are needed to complete any setup or configuration in this sprint and what actions/tickets are needed in future sprints. Monitoring tool documentation is in the following priority order:

Cloudwatch Documentation: https://wiki.emory.edu/display/BDL/Cloudwatch+Documentation
COMPLETE: actions are for team review the document and add a new ticket for AWS Hard Alert paging in ServiceNow.

Thousandeyes Documentation: https://wiki.emory.edu/display/BDL/Thousandeyes+Monitoring
COMPLETE: actions are for team review of the document and schedule ticket #262 for sprint work right before beta launch

Honeybadger Documentation: https://wiki.emory.edu/display/BDL/Honeybadger+Documentation
IN PROGRESS: Collin will do a first draft then the team will review the document for any other actions if needed

**Comment by libdgg** [comment]
Scheduling a working meeting 8/31 at 1pm.

**Comment by libdgg** [comment]
@AGCooper @libah @jcrompton42 @rotated8 
Cloudwatch Documentation: https://wiki.emory.edu/display/BDL/Cloudwatch+Documentation
COMPLETE: actions are for team review the document and add a new ticket for AWS Hard Alert paging in ServiceNow.

Thousandeyes Documentation: https://wiki.emory.edu/display/BDL/Thousandeyes+Monitoring
COMPLETE: actions are for team review of the document and schedule ticket #262 for sprint work right before beta launch

Honeybadger Documentation: https://wiki.emory.edu/display/BDL/Honeybadger+Documentation
IN PROGRESS: Collin will do a first draft then the team will review the document for any other actions if needed

**Comment by rotated8** [comment]
First pass at Honeybadger docs done.
