### ISSUE TITLE
Knowledge for Infrastructure Playbook

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-launch#42]
Infrastructure handoff/knowledge transfer from DCE. This mitigates a project risk that if the middle-ware positions aren’t filled before the end of the project, then application support will be limited, and a significant amount of responsibility will be placed on Ann   

Output: Identify a playbook and workflows for support 
Related info:
[Support Documentation on the Wiki](https://wiki.emory.edu/display/BDL/Operations)

[Finalize the support process flow diagram](https://lucid.app/lucidchart/invitations/accept/inv_c3a1cae6-a58e-4584-8678-0d17b87601e2) (will be used for the OLA)

**Comment by lovinscari** [comment]
I am going to close this ticket as we will need to address how we are going to finish the operational work for Library Search and DLP (and other products) in a different forum.
