### ISSUE TITLE
Review interdependencies of discoverE

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-launch#45]
In order to properly plan for the possible sunsetting of discoverE, a diagram has been created to illustrate the interdependencies of discoverE that must be addressed before the application can be sunsetted.

A meeting has been scheduled to meet with various stakeholders who have direct insight into discoverE interdependencies.

**Comment by tmiles2** [comment]
Pending a review of the action items and outcomes from the initial meeting; a second meeting will need to be schedule.

**Comment by lovinscari** [comment]
Met with team for initial review. @libdgg and I will update diagram based on feedback and will create a new ticket to create a new diagram to show future of interdependencies with Blacklight. Link to [minutes and recording ](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Project%20Management/Ad%20Hoc%20Meetings/Primo%20New%20UI%20Planning/discoverEInterdependencies_072121.docx?d=w293ad11f46ca4a3b866f1b5f190295ba&csf=1&web=1&e=4trxFi)

**Comment by bwatson78** [comment]
@tmiles2 I have viewed this.
