### ISSUE TITLE
Meet with a member of the CCR team to review a high level communications plan

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-launch#48]
In order to start delivering communications to stakeholders regarding changes coming to Blacklight Discovery Layer, an initial meeting is needed with a member of the CCR team who can help determine the completeness of the plan and where CCR might be able to lend assistance.

**Comment by tmiles2** [comment]
@lovinscari I know you had your initial meeting with the CCR team for the beta launch but is this ticket something you want to keep for the production launch or should we close this ticket out?

**Comment by lovinscari** [comment]
Meeting was conducted in September and communications plan was launched in late October.
